### ISSUE TITLE
睡眠问题

### ISSUE THREAD

**Issue by CR7711** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#37]
X250用了你得EFI，就差睡眠无法唤醒问题，唤醒屏幕背光亮黑屏，系统有声音，请问怎样解决，谢谢

**Comment by CLAY-BIOS** [comment]
> X250用了你得EFI，就差睡眠无法唤醒问题，唤醒屏幕背光亮黑屏，系统有声音，请问怎样解决，谢谢

1.在引导界面选择reset nvram清除一下nvram。
2.检查一下你的BIOS设置。

**Comment by CR7711** [comment]
BIOS根据你的设置改的，清理过NVRAM还是一样，无法唤醒

**Comment by CLAY-BIOS** [comment]
> BIOS根据你的设置改的，清理过NVRAM还是一样，无法唤醒

我没有遇到此问题，你是否使用intel无线网卡？
另外，请告诉我你的系统版本。

**Comment by CR7711** [comment]
> > BIOS根据你的设置改的，清理过NVRAM还是一样，无法唤醒
> 
> 我没有遇到此问题，你是否使用intel无线网卡？
> 另外，请告诉我你的系统版本。

使用intel网卡也是这样，现在换了DW1560也是这样，系统版本试过10.15.4，10.15.6 和11.2.3

**Comment by CLAY-BIOS** [comment]
> > > BIOS根据你的设置改的，清理过NVRAM还是一样，无法唤醒
> > 
> > 
> > 我没有遇到此问题，你是否使用intel无线网卡？
> > 另外，请告诉我你的系统版本。
> 
> 使用intel网卡也是这样，现在换了DW1560也是这样，系统版本试过10.15.4，10.15.6 和11.2.3

这就很奇怪了，我在10.14.6，10.15.6，11.2.3中测试过了，没有发现此问题。
尝试将BIOS恢复默认设置。

**Comment by CR7711** [comment]
> > > > BIOS根据你的设置改的，清理过NVRAM还是一样，无法唤醒
> > > 
> > > 
> > > 我没有遇到此问题，你是否使用intel无线网卡？
> > > 另外，请告诉我你的系统版本。
> > 
> > 
> > 使用intel网卡也是这样，现在换了DW1560也是这样，系统版本试过10.15.4，10.15.6 和11.2.3
> 
> 这就很奇怪了，我在10.14.6，10.15.6，11.2.3中测试过了，没有发现此问题。
> 尝试将BIOS恢复默认设置。

也试过恢复BIOS都不行，外接屏可以，现在试试注入EDID看看行不行

**Comment by CLAY-BIOS** [comment]
> > > > > BIOS根据你的设置改的，清理过NVRAM还是一样，无法唤醒
> > > > 
> > > > 
> > > > 我没有遇到此问题，你是否使用intel无线网卡？
> > > > 另外，请告诉我你的系统版本。
> > > 
> > > 
> > > 使用intel网卡也是这样，现在换了DW1560也是这样，系统版本试过10.15.4，10.15.6 和11.2.3
> > 
> > 
> > 这就很奇怪了，我在10.14.6，10.15.6，11.2.3中测试过了，没有发现此问题。
> > 尝试将BIOS恢复默认设置。
> 
> 也试过恢复BIOS都不行，外接屏可以，现在试试注入EDID看看行不行

你可以试试以下操作：
1.唤醒黑屏后，关闭笔记本电脑的机盖然后在打开。
2.尝试开启Hi-DPI，参考: https://github.com/xzhih/one-key-hidpi
3.尝试在BIOS禁用CSM，禁用CSM后启动会花屏，这时让电脑进入睡眠状态，然后再唤醒。

**Comment by CR7711** [comment]
> > > > > > BIOS根据你的设置改的，清理过NVRAM还是一样，无法唤醒
> > > > > 
> > > > > 
> > > > > 我没有遇到此问题，你是否使用intel无线网卡？
> > > > > 另外，请告诉我你的系统版本。
> > > > 
> > > > 
> > > > 使用intel网卡也是这样，现在换了DW1560也是这样，系统版本试过10.15.4，10.15.6 和11.2.3
> > > 
> > > 
> > > 这就很奇怪了，我在10.14.6，10.15.6，11.2.3中测试过了，没有发现此问题。
> > > 尝试将BIOS恢复默认设置。
> > 
> > 
> > 也试过恢复BIOS都不行，外接屏可以，现在试试注入EDID看看行不行
> 
> 你可以试试以下操作：
> 1.唤醒黑屏后，关闭笔记本电脑的机盖然后在打开。
> 2.尝试开启Hi-DPI，参考: https://github.com/xzhih/one-key-hidpi
> 3.尝试在BIOS禁用CSM，禁用CSM后启动会花屏，这时让电脑进入睡眠状态，然后再唤醒。

hi-dpi都开了，禁用CSM也是这样。WIN下是正常的

**Comment by CLAY-BIOS** [comment]
> > > > > > > BIOS根据你的设置改的，清理过NVRAM还是一样，无法唤醒
> > > > > > 
> > > > > > 
> > > > > > 我没有遇到此问题，你是否使用intel无线网卡？
> > > > > > 另外，请告诉我你的系统版本。
> > > > > 
> > > > > 
> > > > > 使用intel网卡也是这样，现在换了DW1560也是这样，系统版本试过10.15.4，10.15.6 和11.2.3
> > > > 
> > > > 
> > > > 这就很奇怪了，我在10.14.6，10.15.6，11.2.3中测试过了，没有发现此问题。
> > > > 尝试将BIOS恢复默认设置。
> > > 
> > > 
> > > 也试过恢复BIOS都不行，外接屏可以，现在试试注入EDID看看行不行
> > 
> > 
> > 你可以试试以下操作：
> > 1.唤醒黑屏后，关闭笔记本电脑的机盖然后在打开。
> > 2.尝试开启Hi-DPI，参考: https://github.com/xzhih/one-key-hidpi
> > 3.尝试在BIOS禁用CSM，禁用CSM后启动会花屏，这时让电脑进入睡眠状态，然后再唤醒。
> 
> hi-dpi都开了，禁用CSM也是这样。WIN下是正常的

试一下以前的版本，看看有没有这个问题。
https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/releases/tag/OpenCore-0.6.6-v2.0

**Comment by 8atm4n** [comment]
感谢作者所做的开发，我的T450S几乎完美的吃上了黑苹果，每次更新几乎只要把EFI进引导分区就可以升级OC，让我少熬了好几个夜晚。
使用过程中唯一出现的问题就是睡眠问题，FN+4只是让笔记本屏幕关闭（无论是否外接显示器），笔记本睡眠后无法唤醒。以上您提到的方法都试了但是没有见效，暂时还没定位到问题所在，所以现在我的解决方案就是不让它睡眠。

**Comment by 8atm4n** [comment]
> > 感谢作者所做的开发，我的T450S几乎完美的吃上了黑苹果，每次更新几乎只要把EFI进引导分区就可以升级OC，让我少熬了好几个夜晚。
> > 使用过程中唯一出现的问题就是睡眠问题，FN+4只是让笔记本屏幕关闭（无论是否外接显示器），笔记本睡眠后无法唤醒。以上您提到的方法都试了但是没有见效，暂时还没定位到问题所在，所以现在我的解决方案就是不让它睡眠。
> 
> 1.告诉我你的系统版本，和使用的无线网卡（intel ？Broadcom?）。
> 2.如果不使用FN + 4 睡眠后能否正常唤醒?
> 3.尝试在引导界面选择reset nvram清除一下nvram，确认你的BIOS设置正确。
> 虽然有人反应这个问题，但我确实没有遇到这个问题。

1.系统版本是Big Sur 11.2.2，无线网卡是intel
2.无论何种形式的睡眠（FN+4、系统菜单睡眠、自动睡眠）都不可以正常唤醒
3.BIOS完全根据您的描述进行修改，且reset nvram无法解决问题。

试验睡眠过程中发现不外接显示器情况按下FN+4，先是笔记本屏幕关闭，30s左右进入真正睡眠模式。在屏幕关闭时间内中FN+4可以点亮屏幕。

**Comment by CLAY-BIOS** [comment]
> > > 感谢作者所做的开发，我的T450S几乎完美的吃上了黑苹果，每次更新几乎只要把EFI进引导分区就可以升级OC，让我少熬了好几个夜晚。
> > > 使用过程中唯一出现的问题就是睡眠问题，FN+4只是让笔记本屏幕关闭（无论是否外接显示器），笔记本睡眠后无法唤醒。以上您提到的方法都试了但是没有见效，暂时还没定位到问题所在，所以现在我的解决方案就是不让它睡眠。
> > 
> > 
> > 1.告诉我你的系统版本，和使用的无线网卡（intel ？Broadcom?）。
> > 2.如果不使用FN + 4 睡眠后能否正常唤醒?
> > 3.尝试在引导界面选择reset nvram清除一下nvram，确认你的BIOS设置正确。
> > 虽然有人反应这个问题，但我确实没有遇到这个问题。
> 
> 1.系统版本是Big Sur 11.2.2，无线网卡是intel
> 2.无论何种形式的睡眠（FN+4、系统菜单睡眠、自动睡眠）都不可以正常唤醒
> 3.BIOS完全根据您的描述进行修改，且reset nvram无法解决问题。
> 
> 试验睡眠过程中发现不外接显示器情况按下FN+4，先是笔记本屏幕关闭，30s左右进入真正睡眠模式。在屏幕关闭时间内中FN+4可以点亮屏幕。

我觉得这可能和intel网卡有关。
试试在BIOS中禁用无线网卡和蓝牙，或者使用Broadcom版本的EFI看看有没有此问题。

**Comment by 8atm4n** [comment]
> > > > 感谢作者所做的开发，我的T450S几乎完美的吃上了黑苹果，每次更新几乎只要把EFI进引导分区就可以升级OC，让我少熬了好几个夜晚。
> > > > 使用过程中唯一出现的问题就是睡眠问题，FN+4只是让笔记本屏幕关闭（无论是否外接显示器），笔记本睡眠后无法唤醒。以上您提到的方法都试了但是没有见效，暂时还没定位到问题所在，所以现在我的解决方案就是不让它睡眠。
> > > 
> > > 
> > > 1.告诉我你的系统版本，和使用的无线网卡（intel ？Broadcom?）。
> > > 2.如果不使用FN + 4 睡眠后能否正常唤醒?
> > > 3.尝试在引导界面选择reset nvram清除一下nvram，确认你的BIOS设置正确。
> > > 虽然有人反应这个问题，但我确实没有遇到这个问题。
> > 
> > 
> > 1.系统版本是Big Sur 11.2.2，无线网卡是intel
> > 2.无论何种形式的睡眠（FN+4、系统菜单睡眠、自动睡眠）都不可以正常唤醒
> > 3.BIOS完全根据您的描述进行修改，且reset nvram无法解决问题。
> > 试验睡眠过程中发现不外接显示器情况按下FN+4，先是笔记本屏幕关闭，30s左右进入真正睡眠模式。在屏幕关闭时间内中FN+4可以点亮屏幕。
> 
> 我觉得这可能和intel网卡有关。
> 试试在BIOS中禁用无线网卡和蓝牙，或者使用Broadcom版本的EFI看看有没有此问题。

已尝试在BIOS中禁用无线网卡及蓝牙，未见效。现在尝试远景论坛中其他解决办法。

**Comment by CLAY-BIOS** [comment]
> > > > > 感谢作者所做的开发，我的T450S几乎完美的吃上了黑苹果，每次更新几乎只要把EFI进引导分区就可以升级OC，让我少熬了好几个夜晚。
> > > > > 使用过程中唯一出现的问题就是睡眠问题，FN+4只是让笔记本屏幕关闭（无论是否外接显示器），笔记本睡眠后无法唤醒。以上您提到的方法都试了但是没有见效，暂时还没定位到问题所在，所以现在我的解决方案就是不让它睡眠。
> > > > 
> > > > 
> > > > 1.告诉我你的系统版本，和使用的无线网卡（intel ？Broadcom?）。
> > > > 2.如果不使用FN + 4 睡眠后能否正常唤醒?
> > > > 3.尝试在引导界面选择reset nvram清除一下nvram，确认你的BIOS设置正确。
> > > > 虽然有人反应这个问题，但我确实没有遇到这个问题。
> > > 
> > > 
> > > 1.系统版本是Big Sur 11.2.2，无线网卡是intel
> > > 2.无论何种形式的睡眠（FN+4、系统菜单睡眠、自动睡眠）都不可以正常唤醒
> > > 3.BIOS完全根据您的描述进行修改，且reset nvram无法解决问题。
> > > 试验睡眠过程中发现不外接显示器情况按下FN+4，先是笔记本屏幕关闭，30s左右进入真正睡眠模式。在屏幕关闭时间内中FN+4可以点亮屏幕。
> > 
> > 
> > 我觉得这可能和intel网卡有关。
> > 试试在BIOS中禁用无线网卡和蓝牙，或者使用Broadcom版本的EFI看看有没有此问题。
> 
> 已尝试在BIOS中禁用无线网卡及蓝牙，未见效。现在尝试远景论坛中其他解决办法。


你能提供一张HacKintool->USB的截图给我吗？

**Comment by 8atm4n** [comment]
> HacKintool->USB

<img width="656" alt="HacKintool- USB" src="https://user-images.githubusercontent.com/11907725/118161211-e9a22380-b451-11eb-936b-e4cc47b44abf.png">

**Comment by CLAY-BIOS** [comment]
> > HacKintool->USB
> 
> <img alt="HacKintool- USB" width="656" src="https://user-images.githubusercontent.com/11907725/118161211-e9a22380-b451-11eb-936b-e4cc47b44abf.png">

我无法找到问题，即使我将所有USB相关的补丁移除，也能正常睡眠唤醒。
另外：睡眠后电源按钮呼吸灯是否能正常闪烁？
尝试一下在USB接口连接一个外置键盘，看看能否从外接键盘唤醒。

**Comment by CLAY-BIOS** [comment]
> > HacKintool->USB
> 
> <img alt="HacKintool- USB" width="656" src="https://user-images.githubusercontent.com/11907725/118161211-e9a22380-b451-11eb-936b-e4cc47b44abf.png">

我无法找到问题，即使我将所有USB相关的补丁移除，也能正常睡眠唤醒。
另外：睡眠后电源按钮呼吸灯是否能正常闪烁？
尝试一下在USB接口连接一个外置键盘，看看能否从外接键盘唤醒。

**Comment by David3434** [comment]
我的t450s x250唤醒睡眠都正常

**Comment by David3434** [comment]
更新下：t450s x250在MAC 10.15.17上唤醒睡眠都正常

在mac 11.14上x250开机后第一次睡眠唤醒正常，再次无法睡眠（过程中呼吸灯会暗一下，就持续变亮，过很久又暗一下，循环重复。再次睡眠也这样情况），T450S正常

我该哪里着手修复 @CLAY-BIOS 

谢谢！

**Comment by BenalexCheung** [comment]
> ### BIOS (1.37):
> - Security -> Security Chip`: Disabled;
> - Memory Protection -> Execution Prevention`: Enabled;
> - Virtualization -> Intel Virtualization Technology`: Enabled;
> - Internal Device Access -> Bottom Cover Tamper Detection`: must be Disabled;
> - Anti-Theft -> Current Setting`: Disabled;
> - Anti-Theft -> Computrace -> Current Setting`: Disabled;
> - Secure Boot -> Secure Boot`: Disabled;
> - UEFI/Legacy Boot`: UEFI Only;
> - CSM Support`: Yes. 

T450s同样遇到睡眠唤醒问题，通过修改上述BIOS配置解决，`fn + 4`即可休眠唤醒
