### ISSUE TITLE
Mojave - Audio not working after sleep

### ISSUE THREAD

**Issue by mybabysexy** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#41]
I downgraded from Big Sur to Mojave.
Audio works fine on first boot, but not working after sleep.
This only happens on Mojave, not Big Sur.
How can I fix this?

**Comment by CLAY-BIOS** [comment]
> I downgraded from Big Sur to Mojave.
> Audio works fine on first boot, but not working after sleep.
> This only happens on Mojave, not Big Sur.
> How can I fix this?

The bin Directory in Big Sur and Catalina is / usr/local/bin/
While the bin directory in Mojave is / usr/bin
In theory, you just need to modify the ALCPlugFix--> install.sh file:
BIN_PATH= / usr/local/bin/ is modified to BIN_PATH= / usr/bin/

**Comment by mybabysexy** [comment]
ok I'll try

**Comment by CLAY-BIOS** [comment]
> ok I'll try

ALCPlugFix -> CLAY.win.ALCPlugFix.plist
The path in the file also needs to be modified

**Comment by mybabysexy** [comment]
like this?
![image](https://user-images.githubusercontent.com/20596043/120746472-7b6cf000-c529-11eb-88df-b0ad43c05d8d.png)

**Comment by mybabysexy** [comment]
still no sound after sleep
![image](https://user-images.githubusercontent.com/20596043/120746923-588f0b80-c52a-11eb-9698-6c11c874278c.png)

**Comment by mybabysexy** [comment]
![image](https://user-images.githubusercontent.com/20596043/120748561-321e9f80-c52d-11eb-8d7e-c40270db7b4a.png)
![image](https://user-images.githubusercontent.com/20596043/120748600-3ea2f800-c52d-11eb-85f8-dd7017d0b62a.png)

**Comment by CLAY-BIOS** [comment]
> still no sound after sleep
> ![image](https://user-images.githubusercontent.com/20596043/120746923-588f0b80-c52a-11eb-9698-6c11c874278c.png)


No sound from the external player, or no sound from the headphones?

**Comment by mybabysexy** [comment]
> > still no sound after sleep
> > ![image](https://user-images.githubusercontent.com/20596043/120746923-588f0b80-c52a-11eb-9698-6c11c874278c.png)
> 
> No sound from the external player, or no sound from the headphones?

No sound from internal speaker, 3.5mm jack loud noise

**Comment by CLAY-BIOS** [comment]
> > > still no sound after sleep
> > > ![image](https://user-images.githubusercontent.com/20596043/120746923-588f0b80-c52a-11eb-9698-6c11c874278c.png)
> > 
> > 
> > No sound from the external player, or no sound from the headphones?
> 
> No sound from internal speaker, 3.5mm jack loud noise

The ALCPlugFix script is used to fix the 3.5mm noise.
As for the speakers having no sound, I ' m not sure what is wrong.
I will install the Mojave to test it.

**Comment by CLAY-BIOS** [comment]
@mybabysexy 
I tested it on Mojave, but I didn't find the problem you said. Audio works normally.

**Comment by mybabysexy** [comment]
can I dump my configurations or something to help you check?

**Comment by CLAY-BIOS** [comment]
> can I dump my configurations or something to help you check?

of course can.

**Comment by mybabysexy** [comment]
what files do you need?

**Comment by CLAY-BIOS** [comment]
> what files do you need?

1.Execute at the terminal：log show --last boot | grep -Ei "Wake"
2.Are you using Intel-WiFi? If so, try disabling it in the BIOS.
3.Execute at the terminal：log show --last boot | grep -Ei "ACPI" 
I need to print the information

**Comment by mybabysexy** [comment]
> > what files do you need?
> 
> 1.Execute at the terminal：log show --last boot | grep -Ei "Wake"
> 2.Are you using Intel-WiFi? If so, try disabling it in the BIOS.
> 3.Execute at the terminal：log show --last boot | grep -Ei "ACPI"
> I need to print the information

[acpi.after-sleep.log](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6607290/acpi.after-sleep.log)
[acpi.before-sleep.log](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6607291/acpi.before-sleep.log)
[wake.after-sleep.log](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6607293/wake.after-sleep.log)
[wake.before-sleep.log](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6607294/wake.before-sleep.log)

**Comment by CLAY-BIOS** [comment]
> > > what files do you need?
> > 
> > 
> > 1.Execute at the terminal：log show --last boot | grep -Ei "Wake"
> > 2.Are you using Intel-WiFi? If so, try disabling it in the BIOS.
> > 3.Execute at the terminal：log show --last boot | grep -Ei "ACPI"
> > I need to print the information
> 
> [acpi.after-sleep.log](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6607290/acpi.after-sleep.log)
> [acpi.before-sleep.log](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6607291/acpi.before-sleep.log)
> [wake.after-sleep.log](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6607293/wake.after-sleep.log)
> [wake.before-sleep.log](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6607294/wake.before-sleep.log)

Sorry, I didn't find anything wrong.
Everything works fine in my tests.
Maybe the reinstallation can be resolved.

**Comment by mybabysexy** [comment]
> > > > what files do you need?
> > > 
> > > 
> > > 1.Execute at the terminal：log show --last boot | grep -Ei "Wake"
> > > 2.Are you using Intel-WiFi? If so, try disabling it in the BIOS.
> > > 3.Execute at the terminal：log show --last boot | grep -Ei "ACPI"
> > > I need to print the information
> > 
> > 
> > [acpi.after-sleep.log](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6607290/acpi.after-sleep.log)
> > [acpi.before-sleep.log](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6607291/acpi.before-sleep.log)
> > [wake.after-sleep.log](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6607293/wake.after-sleep.log)
> > [wake.before-sleep.log](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore/files/6607294/wake.before-sleep.log)
> 
> Sorry, I didn't find anything wrong.
> Everything works fine in my tests.
> Maybe the reinstallation can be resolved.

I tried to reinstall yesterday but audio didn't work after sleep. I'll try Catalina instead

**Comment by mybabysexy** [comment]
Hi, I installed Catalina today but audio isn't recognized, how can I fix this?
Hackintool shows below
![image](https://user-images.githubusercontent.com/20596043/122196679-a3613980-cec1-11eb-9679-82f63b48a94e.png)

**Comment by CLAY-BIOS** [comment]
> Hi, I installed Catalina today but audio isn't recognized, how can I fix this?
> Hackintool shows below
> ![image](https://user-images.githubusercontent.com/20596043/122196679-a3613980-cec1-11eb-9679-82f63b48a94e.png)

Select reset nvram on the boot interface to clear nvram.

**Comment by CLAY-BIOS** [comment]
> Hi, I installed Catalina today but audio isn't recognized, how can I fix this?
> Hackintool shows below
> ![image](https://user-images.githubusercontent.com/20596043/122196679-a3613980-cec1-11eb-9679-82f63b48a94e.png)

Has the problem been solved?

**Comment by mybabysexy** [comment]
Cleared NVRAM and audio detected! Thanks
