### ISSUE TITLE
The brightness works but it can’t goto the maximum brightness

### ISSUE THREAD

**Issue by theadamtube** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#43]
Hello thank you, appreciate your work. Anyways the brightness functions work but whenever I set it to the max in macOS using your efi it is not at its display maximum brightness. I have big sur using someone else’s efi on another hard drive in the laptop and it is much brighter set at the maximum brightness. I also have windows on the drive too and that is brighter too. Why is this?
Model: T450
macOS Version: Monterey (12)
CPU: i5-5300u
Wifi: intel dual band 7265

**Comment by CLAY-BIOS** [comment]
> Hello thank you, appreciate your work. Anyways the brightness functions work but whenever I set it to the max in macOS using your efi it is not at its display maximum brightness. I have big sur using someone else’s efi on another hard drive in the laptop and it is much brighter set at the maximum brightness. I also have windows on the drive too and that is brighter too. Why is this?
> Model: T450
> macOS Version: Monterey (12)
> CPU: i5-5300u
> Wifi: intel dual band 7265

I know the problem.
In previous versions I modified the ACPI patch because of problems with WhateverGreen.kext.
Replace the original patch with this ACPI patch.
[SSDT-PNLF.aml.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/files/6651645/SSDT-PNLF.aml.zip)

**Comment by theadamtube** [comment]
Thank you, also another thing

1. For monterey we should disable  intel Bluetooth firmware and intel Bluetooth injector in config.plist right?

2. For t450 should I disable voodoo2c, etc because I don’t have a touch screen?

**Comment by theadamtube** [comment]
Also should disable Bluetooth in bios

**Comment by CLAY-BIOS** [comment]
> Thank you, also another thing
> 
> 1. For monterey we should disable  intel Bluetooth firmware and intel Bluetooth injector in config.plist right?
> 2. For t450 should I disable voodooi2c, etc because I don’t have a touch screen?

1. You can disable Intel Bluetooth firmware and Intel Bluetooth injectors in config, or disabled Bluetooth directly in BIOS.
2. If you don't use a touch screen, you can disable VoodooI2C and Voodooi2CHID.

**Comment by theadamtube** [comment]
Thank you

**Comment by theadamtube** [comment]
Also why does Monterey feel so slow

**Comment by theadamtube** [comment]
I’m sorry but one more thing, why is the boot time so long

**Comment by theadamtube** [comment]
I replaced the pnfl but brightness still not at max

**Comment by CLAY-BIOS** [comment]
> I replaced the pnfl but brightness still not at max

1. Except for the boot time, I have not noticed any significant slowdown. The specific reason is unknown.
2. Select reset nvram on the boot interface to clear nvram.

**Comment by theadamtube** [comment]
Fixed thank you ❤️
