### ISSUE TITLE
Bluetooth fix

### ISSUE THREAD

**Issue by theadamtube** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#44]
Is your feature request related to a problem? Please describe.
Yes, there is a way to get intel Bluetooth working in Monterey.
A clear and concise description of what the problem is. Bluetooth doesn’t work in Monterey

Describe the solution you'd like
I found this solution in the issues section of the intel Bluetooth repository.
“ Looks like the latest firmware update in commit c52425f is not working properly in macOS Monterey. By reverting the firmware to its previous version, it is working on my setup.

To make Intel Bluetooth working in Monterey, following are needed:

Latest version of Lilu (from source)
Latest version of BrcmPatchRAM (from source), only need BlueToolFixup.kext in this package
IntelBluetoothFirmware.kext with older firmware (Can be built from https://github.com/pigworlds/IntelBluetoothFirmware/tree/revertfw)
IntelBluetoolInjector.kext is not needed.
Shutdown and restart machine instead of reboot.
Tested on Wireless-AC 8265 and Wireless-AC 9560 with streaming audio to Bluetooth headset.”

**Comment by CLAY-BIOS** [comment]
> Is your feature request related to a problem? Please describe.
> Yes, there is a way to get intel Bluetooth working in Monterey.
> A clear and concise description of what the problem is. Bluetooth doesn’t work in Monterey
> 
> Describe the solution you'd like
> I found this solution in the issues section of the intel Bluetooth repository.
> “ Looks like the latest firmware update in commit c52425f is not working properly in macOS Monterey. By reverting the firmware to its previous version, it is working on my setup.
> 
> To make Intel Bluetooth working in Monterey, following are needed:
> 
> Latest version of Lilu (from source)
> Latest version of BrcmPatchRAM (from source), only need BlueToolFixup.kext in this package
> IntelBluetoothFirmware.kext with older firmware (Can be built from https://github.com/pigworlds/IntelBluetoothFirmware/tree/revertfw)
> IntelBluetoolInjector.kext is not needed.
> Shutdown and restart machine instead of reboot.
> Tested on Wireless-AC 8265 and Wireless-AC 9560 with streaming audio to Bluetooth headset.”

Thank you very much!
I will keep this question open so that I can help others.
