### ISSUE TITLE
你好，big sur从11.4升级到11.5.1后，开机出现OCB: StartImage failed Aborted

### ISSUE THREAD

**Issue by PanjiLovePanda** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#50]
11.4的时候用着好的，升级到11.5.1就出现问题，百度搜索过后我以为是固态硬盘不兼容，就在机械硬盘上重新安装了一边big sur11.4，使用没问题，升级到11.5.1以后又出现标题出现的问题。

**Comment by CLAY-BIOS** [comment]
> 11.4的时候用着好的，升级到11.5.1就出现问题，百度搜索过后我以为是固态硬盘不兼容，就在机械硬盘上重新安装了一边big sur11.4，使用没问题，升级到11.5.1以后又出现标题出现的问题。

我没有遇到此问题，你使用的是最新版本的EFI文件吗？

**Comment by PanjiLovePanda** [comment]
emmm……替换了新的efi还是一样问题，不纠结了我用11.4版本

**Comment by CLAY-BIOS** [comment]
> emmm……替换了新的efi还是一样问题，不纠结了我用11.4版本。其他很完美，谢谢大神

1.如果你有时间的话，可以试试新版本，看看是否有此问题。
2.如果你找到导致此问题的原因或者有新的进展，请告诉我。

**Comment by PanjiLovePanda** [comment]
大佬你好，后来我退回bigsur11.4试了你之前的efi都不行了出现了上述问题，安装的时候能正常进界面，重启的时候不行了，所以不是bigsur版本问题。后来我找到这位作者的efi，能进系统了，我和他是同样的网卡dw1560，你的是dw1820，难道是因为这个原因？。我也将你的config和他的config用occ打开比较了下，因为我才疏学浅没发现原因，他的配置内容比较精简。我喜欢你的efi，希望得到你的帮助，非常感谢！。该作者efi：https://github.com/findyy99/ThinkPad-T450S-Hackintosh-macOS-Big-Sur

**Comment by PanjiLovePanda** [comment]
插耳机有杂音，关上盖子睡眠再打开就没有了，使用了你提供了alcplugfix，也没效果，是不是我使用方法不对？
![截屏2021-08-12 07 38 15](https://user-images.githubusercontent.com/62539517/129216381-b52bed6f-0f13-46f0-ba9c-39a21cb4d22a.png)

**Comment by CLAY-BIOS** [comment]
> 插耳机有杂音，关上盖子睡眠再打开就没有了，使用了你提供了alcplugfix，也没效果，是不是我使用方法不对？
> ![截屏2021-08-12 07 38 15](https://user-images.githubusercontent.com/62539517/129216381-b52bed6f-0f13-46f0-ba9c-39a21cb4d22a.png)

权限不够，用 sudo ./install.sh

**Comment by PanjiLovePanda** [comment]
> 插耳机有杂音，关上盖子睡眠再打开就没有了，使用了你提供了alcplugfix，也没效果，是不是我使用方法不对？
> ![截屏2021-08-12 07 38 15](https://user-images.githubusercontent.com/62539517/129216381-b52bed6f-0f13-46f0-ba9c-39a21cb4d22a.png)

**Comment by PanjiLovePanda** [comment]
> 。

谢谢大佬，现在都好了，使用完美
