### ISSUE TITLE
扩展坞-睡眠

### ISSUE THREAD

**Issue by jack338c** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#51]
您好！大神
最近使用扩展坞，发现无法睡眠。用的是big sur 11.4(wind10下可以睡眠)
另外，在用扩展坞条件下，在盒上盖子后（用软件启用不睡眠），蓝牙（dw1820a)会短暂与蓝牙耳机失联无声，但是重新关闭，开启蓝牙耳机后又正常。
再次打卡盖子后，蓝牙失声现象又重现，需要重复操作。

先反馈下，有空请大神帮查证下
谢谢了！

**Comment by CLAY-BIOS** [comment]
> 您好！大神
> 最近使用扩展坞，发现无法睡眠。用的是big sur 11.4(wind10下可以睡眠)
> 另外，在用扩展坞条件下，在盒上盖子后（用软件启用不睡眠），蓝牙（dw1820a)会短暂与蓝牙耳机失联无声，但是重新关闭，开启蓝牙耳机后又正常。
> 再次打卡盖子后，蓝牙失声现象又重现，需要重复操作。
> 
> 先反馈下，有空请大神帮查证下
> 谢谢了！

在config.plist->ACPI 中勾选 SSDT-IGBE补丁即可修复扩展坞睡眠问题，但使用SSDT-IGBE补丁后无法使用翻盖模式。

**Comment by jack338c** [comment]
好的，我试试
非常感谢！
