### ISSUE TITLE
Windows 11 Compatibility

### ISSUE THREAD

**Issue by nycxbro527** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#52]
Thank for all your great work! I've been reading up on Windows 11 requirements - it says it's going to require both TPM and Secure Boot enabled in the BIOS. Just turned on TPM on my T450s and it doesn't affect the macOS Boot (11.5.1). But to turn on Secure Boot, CSM Support needs to be disabled which messes up the boot. Do you think you'll make change to the EFI in the future or will Win11 boot be impossible?

**Comment by Cxistiro** [comment]
just turn on secure boot and install windows 11 and then turn it off again. plus i install windows 11 without secure boot enabled. all i needed was intel ptt (tpm 2) to be enabled.

**Comment by Cxistiro** [comment]
turning secure boot on actually made it so i COULDNT boot windows 11.

**Comment by Cxistiro** [comment]
tpm checks only occur during windows 11 installation

**Comment by nycxbro527** [comment]
Thanks @Cxistiro. Just the answer I was looking for
