### ISSUE TITLE
新版可能有问题

### ISSUE THREAD

**Issue by jack338c** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#55]
大神好！反馈1个问题

最近更新了你的最新版Lenovo-ThinkPad-T450s-Hackintosh-OpenCore使用后发现： chrome、微信等程序好好用着时候，偶然点击它时，突然就闪退了，再点击程序图标就再也打不开了（在那里跳跃，但就是无法呈现）

本人的x250 ,t450s 都有这个问题
但之前的老版本没有这个问题

**Comment by CLAY-BIOS** [comment]
> 大神好！反馈1个问题
> 
> 最近更新了你的最新版Lenovo-ThinkPad-T450s-Hackintosh-OpenCore使用后发现： chrome、微信等程序好好用着时候，偶然点击它时，突然就闪退了，再点击程序图标就再也打不开了（在那里跳跃，但就是无法呈现）
> 
> 本人的x250 ,t450s 都有这个问题
> 但之前的老版本没有这个问题

我刚刚在macos中进行了两个小时左右的测试。一切正常，没有遇到闪退的问题。
我会继续追踪这个问题，如果你有更详细的信息请告诉我。

**Comment by jack338c** [comment]
@CLAY-BIOS 
好的，谢谢答复
然后补充下：
1系统目前是11.5.2，之前11.5.x,都有我描述的问题
2用的是DW1820A，linux windows mac同一硬盘上
不知道是不是软件冲突，或者内存什么的引起的

**Comment by CLAY-BIOS** [comment]
> @CLAY-BIOS
> 好的，谢谢答复
> 然后补充下：
> 1系统目前是11.5.2，之前11.5.x,都有我描述的问题
> 2用的是DW1820A，linux windows mac同一硬盘上
> 不知道是不是软件冲突，或者内存什么的引起的

我更新了OpenCore 0.7.3, 你可以试试它。

**Comment by jack338c** [comment]
> > @CLAY-BIOS
> > 好的，谢谢答复
> > 然后补充下：
> > 1系统目前是11.5.2，之前11.5.x,都有我描述的问题
> > 2用的是DW1820A，linux windows mac同一硬盘上
> > 不知道是不是软件冲突，或者内存什么的引起的
> 
> 我更新了OpenCore 0.7.3, 你可以试试它。

已用上！
非常感谢！！
