### ISSUE TITLE
Need hint for fixing Wifi

### ISSUE THREAD

**Issue by charlie-mtl** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#56]
Hi Clay-Bios,

Thanks a lot for this great repos.
I have a x250 i5 5300U with an Intel 7265AC card. Would you please guide me on how to make the wifi functional?
I've installed Big sur and copied your EFI as it is.
Any help would be much appreciated.
Another QQ, I also have a T470s i5 7300U with a Intel 8265NGW, I was wondering if it would be to much asking to have it to your repos?

Thank you gain.
Charlie

**Comment by CLAY-BIOS** [comment]
> Hi Clay-Bios,
> 
> Thanks a lot for this great repos.
> I have a x250 i5 5300U with an Intel 7265AC card. Would you please guide me on how to make the wifi functional?
> I've installed Big sur and copied your EFI as it is.
> Any help would be much appreciated.
> Another QQ, I also have a T470s i5 7300U with a Intel 8265NGW, I was wondering if it would be to much asking to have it to your repos?
> 
> Thank you gain.
> Charlie

Just download the Intel version of EFI from this page, and you don’t need to do anything else.
https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/releases/tag/OpenCore-0.7.2-v2.8

**Comment by charlie-mtl** [comment]
I feel so !$#$#$%!@$

Thanks a lot.
Any way I can help?   don't hesitate.
Thank you again.
Charlie
