### ISSUE TITLE
x250使用dw1820a，WiFi在macOS 11.6下工作不正常

### ISSUE THREAD

**Issue by jhcbl** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#61]
蓝牙可以使用
WiFi异常，无法搜索到任何网络，且设置-网络中无法看到WiFi

**Comment by CLAY-BIOS** [comment]
> 蓝牙可以使用
> WiFi异常，无法搜索到任何网络，且设置-网络中无法看到WiFi

我在macOS 11.6和macOS 11.6.1中测试了dw1820a，没有遇到对你说的问题。
1.在引导界面选择reset nvram，清除nvram。
2.插上网线，中终端中执行sh -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/Hackintosh/master/Tools/DW1820A)"
把结果发上来。

**Comment by CLAY-BIOS** [comment]
> 我的是t450s，使用的网卡是dw1820a 00jt494。在11.6上刚装上网卡时不能驱动蓝牙，但是wifi正常，后来在win10系统中把蓝牙打开，在重启到bigsur系统中可以正常驱动蓝牙了。但是蓝牙连接蓝牙耳机时和2.4g wifi干扰很严重，网络有流量时会导致蓝牙耳机很卡顿，不知道有没有解决办法。

dw1820a这种双天线网卡就是这样的，蓝牙和2.4g wifi使用同一根天线，你只有使用5g wifi才能解决这个问题。
