### ISSUE TITLE
Black screen after picker - Thinkpad X250

### ISSUE THREAD

**Issue by dessenag** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#62]
As per title, after the picker I get a stationary black screen with no verbose until timeout is reached.
I attach the config.plist (which has been modified only for debugging purposes) and the debug entry.
I am able and willing to provide more information, if needed

[opencore-2021-10-20-165335.txt](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/files/7382419/opencore-2021-10-20-165335.txt)
[config.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/files/7382423/config.zip)

.

**Comment by CLAY-BIOS** [comment]
> Hi, thank you. However, this did not solve the issue. Still stuck on a black screen after picker at the same code:
> OCDI: Built DMG DP: VenHw

Tell me your system version and network card model.
Try disabling Bluetooth in BIOS.
