### ISSUE TITLE
Black screen on 2560x1440 panel on x1c3

### ISSUE THREAD

**Issue by Sakura-kun** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#63]
Thanks so much for this build first of all. I had everything working in about 15 minutes under Big Sur and i appreciate the work put into this. Intel wifi and bluetooth both working, ThinkPad Dock Pro works like it was build for this, and i had zero issues with audio, which is a nice surprise.
The only wired thing is that i had to close and open the lid back up in order to get the display after the first part of the loading process (both installer and installed system). Messing around with one-key-hidpi resulted in:
1. Enable HIDPI: Acting the same as before, but waking from sleep properly.
2. Enable HIDPI (with EDID): Working properly after boot, but then showing the black screen after i woke the machine from sleep and typed in the password.

Any advice would be appreciated)

P.S.
I also have a DW1820A card at hand, witch i can test out, in case there's some PCI black magic that freaks up the display.

**Comment by spurd0** [comment]
Hi @CLAY-BIOS ! 
Thanks for your work, it's amazing, setting up hackintosh for my X1C3 took only hour. Great manual!
I have same machine as @Sakura-kun with 2560x1440 display. And i have same issue. Got black screen after booting, have to turn it off using Ctrl+Shift+Insert key and then press some button for turning on. 
I noticed that screen is just blank (with backlight) and it's completly turrning off after pressing key combination.
Any ideas?
I'm getting this issue on every mac os versions. Also tried https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-x1-carbon-gen-3-2015-model-using-clover-uefi.251383 this manual, had same issue. 
Screen can be turned back by sleep and wake up or key combination.
Setting graphics memory to 512MB doesn't resolve problem.
Setting lower resolution in OSX Settings also doesn't resolve problem.

**Comment by CLAY-BIOS** [comment]
> Hi @CLAY-BIOS ! Thanks for your work, it's amazing, setting up hackintosh for my X1C3 took only hour. Great manual! I have same machine as @Sakura-kun with 2560x1440 display. And i have same issue. Got black screen after booting, have to turn it off using Ctrl+Shift+Insert key and then press some button for turning on. I noticed that screen is just blank (with backlight) and it's completly turrning off after pressing key combination. Any ideas? I'm getting this issue on every mac os versions. Also tried https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-x1-carbon-gen-3-2015-model-using-clover-uefi.251383 this manual, had same issue. Screen can be turned back by sleep and wake up or key combination. Setting graphics memory to 512MB doesn't resolve problem. Setting lower resolution in OSX Settings also doesn't resolve problem.

Sorry, I don't know how to solve this problem.
I've enabled all the functions on the core graphics card,The only thing I'm not sure about is the device ID.
1. You can try to change this value to 16260006 to try to use a larger VRAM.
![微信截图_20220518212231](https://user-images.githubusercontent.com/54008255/169050490-45986e59-4fdb-44ec-89cd-8ab4d33afa62.png)
2. Reference: https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#support-all-possible-core-display-clock-cdclk-frequencies-on-icl-platforms With this manual, try to modify the device ID, which may solve this problem.

**Comment by spurd0** [comment]
Thanks for fast reply, tried to change `device-id`, no success.
Also tried different flags such as `-igfxmpc`, `-igfxbls`, `-cdfon`.
Bug is not critical, will leave it as is. Thanks one more time for your help!

**Comment by spurd0** [comment]
Was able to fix problem using [one-key-hidpi](https://github.com/xzhih/one-key-hidpi).
I have already tried it during debugging before, but no success. Now i was able to fix it using the next settings:
<img width="569" alt="Screenshot 2022-06-01 at 17 46 37" src="https://user-images.githubusercontent.com/21377875/171389630-7da7aceb-cb8c-4f55-90a4-91a57c5e748d.png">
Unfortunatelly, display icon won't be replaced so you may skip that step.
Use ctrl+shift+insert in order to power off display and then press some button to turn it one during installation. Or you may try to close\open lid. Good luck!
Also disabled AMT (Selected "Disabled" option) in BIOS. But not sure that's connected with the issue.
UPD: now i have problem with waking up laptop... Like in original post. Problem still unresolved.
