### ISSUE TITLE
Monterey Setup failed on T450S

### ISSUE THREAD

**Issue by ATX3000** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#65]
Hi, I had a T450s ( core i5 4200u), and i have setup big sure before with an other files.
its works perfectly but teh update of monterey don't works (final  reboot no change anything)

I have try several time to setup with this present files, opencore efi 0.74 etc.

With file for no wifi intel: it's ok but no wifi enabled at end ot setup, after, i have check config plist and drivers with comparison with my previous version of kext, i have try many thing, many setup trying but no wifi works. ( boradcom) ( i have try to setup with bluetooth card disabled on bios setup etc: it's the same)

With the file with wifi intel it's make a long time to enter in monterey setup but the ssd not detected.

I think that's monterey official release don't works like the beta or rc release with the files present, opencore or kext.

**Comment by ATX3000** [comment]
I have try with the last update of files  0.7.5 but wifi isn't detected

**Comment by CLAY-BIOS** [comment]
> I have try with the last update of files 0.7.5 but wifi isn't detected

Execute at terminal
sh -c "$(curl -fsSL https://cdn.jsdelivr.net/gh/daliansky/Hackintosh/Tools/BCM94360Z4)"
Post the results

**Comment by ATX3000** [comment]
hI, this is the results


  ######   #####  #     #  #####  #        #####   #####    ###   ####### #
  #     # #     # ##   ## #     # #    #  #     # #     #  #   #       #  #    #
  #     # #       # # # # #     # #    #        # #       # #   #     #   #    #
  ######  #       #  #  #  ###### #######  #####  ######  #  #  #    #    #######
  #     # #       #     #       #      #        # #     # #   # #   #          #
  #     # #     # #     # #     #      #  #     # #     #  #   #   #           #
  ######   #####  #     #  #####       #   #####   #####    ###   #######      #
 BCM94360Z4驱动信息： 
 macOS版本:  11.6
 引导参数:   "-v -iosd3v3 -carbeta"
===========================================================
 机型或主板:   网卡信息： 
===========================================================
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
 蓝牙信息： 
===========================================================
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
as.lvs1974.AirportBrcmFixup (2.1.4)
as.acidanthera.BrcmFirmwareStore (2.6.1)

**Comment by CLAY-BIOS** [comment]
> hI, this is the results
> 
> ###### ##### # # ##### # ##### ##### ### #######
> # # # # ## ## # # # # # # # # # # # #
> # # # # # # # # # # # # # # # # # #
> ###### # # # # ###### ####### ##### ###### # # # #
> # # # # # # # # # # # # # #
> # # # # # # # # # # # # # # # #
> ###### ##### # # ##### # ##### ##### ### #######
> # BCM94360Z4驱动信息：
> macOS版本: 11.6
> 引导参数: "-v -iosd3v3 -carbeta"
> # 机型或主板: 网卡信息：
> # Executing: /usr/bin/kmutil showloaded
> No variant specified, falling back to release
> 蓝牙信息：
> Executing: /usr/bin/kmutil showloaded No variant specified, falling back to release as.lvs1974.AirportBrcmFixup (2.1.4) as.acidanthera.BrcmFirmwareStore (2.6.1)

After installation, open hackintool and find the PCIe option.
Take a screenshot and send it to me.
[Hackintool.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/files/7492153/Hackintool.zip)

**Comment by ATX3000** [comment]
![image](https://user-images.githubusercontent.com/93343345/140657218-2e045d36-4edd-4436-89ba-c03f9ff378dd.png)

**Comment by ATX3000** [comment]
Please view here thanks you very much

**Comment by CLAY-BIOS** [comment]
> Please view here thanks you very much

Try this EFI file.
[EFI.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore/files/7495454/EFI.zip)

**Comment by ATX3000** [comment]
- I have try new setup, wifi works now thank you very much!!

 Can you explain to me the difference between the bios available on github?
- what have you made? 

- For Bluetooth, after enable on bios, how can i activate it?

Thanks you very much for your help

**Comment by ATX3000** [comment]
Can I configure and install my software to then be able to debug bluetooth? or do you think it will be necessary to redo a complete reinstallation with another EFI.
Thank you so much !!

**Comment by ATX3000** [comment]
Today i have try to setup with your efi.zip monterey and wifi not detected, last time, i have inversed usb key, i think that i have put efi file with usb setup of macos big sur, after the panel of setting  language, wifi logo was enable.
I have make the test, the efi file works ( wifi ok) with big sur but not with monterey setup...

**Comment by ATX3000** [comment]
Thanks for help
