### ISSUE TITLE
Sierra Wireless EM7345 4G LTE detected as ethernet

### ISSUE THREAD

**Issue by TymEK49** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#70]
Hi, first of all - thanks, your efi is stable even with intel wifi card. 
However my build in 4G WWAN card is detected as etherent not as wwan.
![Screenshot 2021-11-22 at 12 48 04](https://user-images.githubusercontent.com/10456488/142856531-824408f0-e64d-4ed9-9823-fe9eb87e2183.png)
Can you help me?

**Comment by CLAY-BIOS** [comment]
> Hi, first of all - thanks, your efi is stable even with intel wifi card.
> However my build in 4G WWAN card is detected as etherent not as wwan.
> ![Screenshot 2021-11-22 at 12 48 04](https://user-images.githubusercontent.com/10456488/142856531-824408f0-e64d-4ed9-9823-fe9eb87e2183.png)
> Can you help me?

This is because the EM7345 4G LTE card does not have a corresponding driver in macOS and macOS cannot correctly recognize it.
