### ISSUE TITLE
升级efi

### ISSUE THREAD

**Issue by izshui** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#71]
您好，笔记本是x250，之前用您的efi成功安装，现在想替换成您最新发布的efi文件，直接替换的话，引导就没有了，想问一下，更换最新efi文件是否还需要别的流程！

**Comment by CLAY-BIOS** [comment]
> 您好，笔记本是x250，之前用您的efi成功安装，现在想替换成您最新发布的efi文件，直接替换的话，引导就没有了，想问一下，更换最新efi文件是否还需要别的流程！

抱歉！我没有遇到你说的问题，直接替换就行了。
