### ISSUE TITLE
Boot issue on last efi 

### ISSUE THREAD

**Issue by juanpy0223** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#72]
Hello, first, I want to thank you for your gift to all of us, thank you very much....

I downloaded your last efi... When I try to boot I get an error saying that SSDT-TEMP.aml could not be found. And after that boot process is slow, it takes about 4 minutes to reach macOS login screen... Im using your Open Core 0.6.6 efi, and it works like a charm, just wanted to test a newer version to see if it was different... Do you have any suggestion?

My specs are: LENOVO T450, i5-5500u, 16gm ram, evo 850 500gb ssd, screen 1920*1080

**Comment by CLAY-BIOS** [comment]
> Hello, first, I want to thank you for your gift to all of us, thank you very much....
> 
> I downloaded your last efi... When I try to boot I get an error saying that SSDT-TEMP.aml could not be found. And after that boot process is slow, it takes about 4 minutes to reach macOS login screen... Im using your Open Core 0.6.6 efi, and it works like a charm, just wanted to test a newer version to see if it was different... Do you have any suggestion?
> 
> My specs are: LENOVO T450, i5-5500u, 16gm ram, evo 850 500gb ssd, screen 1920*1080

Try selecting Reset nvram on the boot screen to clear nvRAM and make sure your BIOS Settings are correct.

**Comment by juanpy0223** [comment]
Ok thanks
