### ISSUE TITLE
Broadcom wifi no signal on windows 10

### ISSUE THREAD

**Issue by juanpy0223** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#73]
Hello, I installed a BCM94360ng on my lenovo t450, it works great on macOS, no kext or config needed, but on windows it says NO WIFI NETWORK DETECTED... i tried several drivers and no lock, do you have any suggestion?... I also tried a genuine one taken from a macbookair (bcm94360cs2 + a+e adapter), and the same happens

**Comment by CLAY-BIOS** [comment]
> Hello, I installed a BCM94360ng on my lenovo t450, it works great on macOS, no kext or config needed, but on windows it says NO WIFI NETWORK DETECTED... i tried several drivers and no lock, do you have any suggestion?... I also tried a genuine one taken from a macbookair (bcm94360cs2 + a+e adapter), and the same happens

In ThinkPad, all Apple cards except bcm94360cd cannot work properly in win10 and Linux.
Bcm94360cd can work normally in win10, but this card is too large to fit into the notebook.
I suggest you replace the network card with dw1820a or dw1830.

**Comment by juanpy0223** [comment]
Ok thank you, the bcm94360ng works great both in macos as in windows 10, when I put it on my Lenovo e570, the problem is only with the t440s and the t450
