### ISSUE TITLE
x250v0.7.5 EFI 能安装进系统，再次开机无法识别启动，进windows10，也会系统及不稳定。

### ISSUE THREAD

**Issue by klzbw** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#77]
![4D7CAC37-D25E-44CF-BDC3-0C1C2C7054DB](https://user-images.githubusercontent.com/11423680/144954154-7cbe9493-536a-4c94-98ed-82598f24bc4a.jpeg)

**Comment by CLAY-BIOS** [comment]
> ![4D7CAC37-D25E-44CF-BDC3-0C1C2C7054DB](https://user-images.githubusercontent.com/11423680/144954154-7cbe9493-536a-4c94-98ed-82598f24bc4a.jpeg)

Try selecting Reset nvram on the boot screen to clear nvRAM and make sure your BIOS Settings are correct.
