### ISSUE TITLE
Bluetooth doesn't work on X250

### ISSUE THREAD

**Issue by mrrfv** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#78]
Enabling Bluetooth doesn't work (nothing happens upon clicking the "turn on" button). Hackintool doesn't show any Bluetooth devices either.

I'm on a ThinkPad x250 running macOS Monterey with Intel Bluetooth.

**Comment by xtsui** [comment]
Try entre to Windows system and check the Bluetooth, then back to MacOS. Because I had the same problem before.

**Comment by xtsui** [comment]
> Enabling Bluetooth doesn't work (nothing happens upon clicking the "turn on" button). Hackintool doesn't show any Bluetooth devices either.
> 
> I'm on a ThinkPad x250 running macOS Monterey with Intel Bluetooth.

Try entre to Windows system and check the Bluetooth, then back to MacOS. Because I had the same problem before.

**Comment by CLAY-BIOS** [comment]
> Enabling Bluetooth doesn't work (nothing happens upon clicking the "turn on" button). Hackintool doesn't show any Bluetooth devices either.
> 
> I'm on a ThinkPad x250 running macOS Monterey with Intel Bluetooth.

1. Confirm that Bluetooth is not disabled in BIOS.
2. Check whether Bluetooth can be used in windows.

**Comment by mrrfv** [comment]
1. It's not disabled
2. It works just fine on Windows.

I've found that Bluetooth works fine on macOS Big Sur, but not on Monterey.

Related issues:
https://github.com/acidanthera/bugtracker/issues/1821
https://github.com/acidanthera/bugtracker/issues/1669

**Comment by mrrfv** [comment]
I replaced AirportItlwm.kext with Itlwm.kext and everything's working fine now.
