### ISSUE TITLE
Bigger widgets are glitched out (Monterey OC0.7.5 Version)

### ISSUE THREAD

**Issue by BlackOtton** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#79]
Hey. I encountered a weird issue with macOS Monterey on my T450s, using this EFI (although I don't know if it's limited only to this one). 
The widgets I'm talking about normally, look like this:

![1](https://user-images.githubusercontent.com/52571671/145633310-c477909e-40b9-47a7-a939-82b37a7fa68e.jpg)

However, if I set the weather widget as big one, whole OS stalls for couple of seconds and this shows up:

![2](https://user-images.githubusercontent.com/52571671/145633529-530351ee-24cf-4e2f-ae2c-ae00acc275b3.jpg)

And this is how widgets gallery shows up as after this:

![3](https://user-images.githubusercontent.com/52571671/145633657-842fcfb9-a434-4cee-9550-177d63f08bd5.jpg)

Sometimes, they show up completely glitched out as above:

![4](https://user-images.githubusercontent.com/52571671/145633918-f20d616a-c242-4fa8-9f2e-523acd281570.jpg)

The only option to get them back to work (except restarting), is to change back widget size to medium, and kill Notification Center in Activity Monitor.

So far, I tried changing Video Memory Size in BIOS, but to no avail.
Is there any way to fix that?

My T450s specifications:

- i5 5300U
- 8GB DDR3
- Intel HD 5500

**Comment by CLAY-BIOS** [comment]
> Hey. I encountered a weird issue with macOS Monterey on my T450s, using this EFI (although I don't know if it's limited only to this one). The widgets I'm talking about normally, look like this:
> 
> ![1](https://user-images.githubusercontent.com/52571671/145633310-c477909e-40b9-47a7-a939-82b37a7fa68e.jpg)
> 
> However, if I set the weather widget as big one, whole OS stalls for couple of seconds and this shows up:
> 
> ![2](https://user-images.githubusercontent.com/52571671/145633529-530351ee-24cf-4e2f-ae2c-ae00acc275b3.jpg)
> 
> And this is how widgets gallery shows up as after this:
> 
> ![3](https://user-images.githubusercontent.com/52571671/145633657-842fcfb9-a434-4cee-9550-177d63f08bd5.jpg)
> 
> Sometimes, they show up completely glitched out as above:
> 
> ![4](https://user-images.githubusercontent.com/52571671/145633918-f20d616a-c242-4fa8-9f2e-523acd281570.jpg)
> 
> The only option to get them back to work (except restarting), is to change back widget size to medium, and kill Notification Center in Activity Monitor.
> 
> So far, I tried changing Video Memory Size in BIOS, but to no avail. Is there any way to fix that?
> 
> My T450s specifications:
> 
> * i5 5300U
> * 8GB DDR3
> * Intel HD 5500

This problem does exist. This may be a bug in Monterey, and I may not be able to fix it.

**Comment by BlackOtton** [comment]
Thanks for the reply. I understand, seems like this might be macOS problem. I will update to the newer version of Monterey and see if that would help.
Thanks

**Comment by dkoluris** [comment]
I have the same problem with my own repo: https://github.com/dkoluris/HP-PROBOOK-470-G2-OpenCore
I am too using HD5500 and have that same weather widget glitch.
No ideas as of yet, right?

**Comment by BlackOtton** [comment]
Yes, updating to newer version of Monterey doesn't change anything.
