### ISSUE TITLE
接投影仪色彩不正常

### ISSUE THREAD

**Issue by jack338c** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#80]
大神好！
最近发现T450S或X250（都是BIG SUR)接投影仪看电影色彩都偏暗，而接外部液晶显示器都是正常的
但是WINDOWS下接投影仪色彩全正常
请问这个是什么原因，有办法解决吗？

谢谢！

**Comment by CLAY-BIOS** [comment]
> 大神好！ 最近发现T450S或X250（都是BIG SUR)接投影仪看电影色彩都偏暗，而接外部液晶显示器都是正常的 但是WINDOWS下接投影仪色彩全正常 请问这个是什么原因，有办法解决吗？
> 
> 谢谢！

我不使用投影仪，因此我不知道发生了什么。
在投影设备中应该和显示器一样可以设置颜色描述文件
![截屏2021-12-18 上午12 10 36](https://user-images.githubusercontent.com/54008255/146574444-2ea715e0-6bb8-415a-a1cf-1dd908e6bbec.png)

**Comment by jack338c** [comment]
好的，感谢提供思路
我到时试试看

**Comment by jack338c** [comment]
大神好！
我这个截图你帮看下，是正常的吗，和你发的不一样，是不是版本关系？没有可以调色地方
![Screen Shot 2022-01-06 at 1 59 39 PM](https://user-images.githubusercontent.com/10782586/148340293-11f05efa-c010-439b-9f0b-3fd1ac9cee5f.png)

**Comment by CLAY-BIOS** [comment]
> 大神好！ 我这个截图你帮看下，是正常的吗，和你发的不一样，是不是版本关系？没有可以调色地方 ![Screen Shot 2022-01-06 at 1 59 39 PM](https://user-images.githubusercontent.com/10782586/148340293-11f05efa-c010-439b-9f0b-3fd1ac9cee5f.png) ![Screen Shot 2022-01-06 at 1 59 16 PM](https://user-images.githubusercontent.com/10782586/148340411-34e9e191-74ba-45ba-858c-892eba066185.png)

可能是不支持。

**Comment by jack338c** [comment]
好的，明白了
谢谢！
