### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by koleszka998** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#81]
I have black screen after i choose macOS recovery in picker.
Lenovo Thinkpad x250

**Comment by CLAY-BIOS** [comment]
> I have black screen after i choose macOS recovery in picker.
> Lenovo Thinkpad x250

Check that your BIOS Settings are correct.

**Comment by koleszka998** [comment]
yeah everything is correct but your 0.7.6 is bugged af 0.7.5 works good

**Comment by yxyshadow** [comment]
Thinkpad X250 测了0.75和0.76两个版本EFI，bigsur11.6.2睡眠黑屏后，键盘鼠标触摸板电源按键皆无法唤醒，电源键一闪一亮只能强制关机。EFI仅按教程修改了WiFi和蓝牙的勾选项，BIOS也按教程设置，特来反馈及寻求帮助。

**Comment by CLAY-BIOS** [comment]
> Thinkpad X250 测了0.75和0.76两个版本EFI，bigsur11.6.2睡眠黑屏后，键盘鼠标触摸板电源按键皆无法唤醒，电源键一闪一亮只能强制关机。EFI仅按教程修改了WiFi和蓝牙的勾选项，BIOS也按教程设置，特来反馈及寻求帮助。

尝试在启动界面上选择Reset nvram来清除nvram。

**Comment by yxyshadow** [comment]
谢谢，已重置nvram，我测试一段时间看看。

**Comment by snami100** [comment]
I also got black screen on t450s. With same BIOS Version and all the settings...

**Comment by snami100** [comment]
> yeah everything is correct but your 0.7.6 is bugged af 0.7.5 works good

how did you solved it?
