### ISSUE TITLE
扩展坞外接2K显示器亮5秒就黑屏

### ISSUE THREAD

**Issue by findyy99** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#82]
- 本子是T450s。
- 最新的版本EFI。
- 扩展坞为40A2，固件最新。
- 外接显示器为DELL P2418D，2K 60HZ。
- 连接线尝试过HDMI和DP。
故障现象为识别显示器亮屏5秒左右，显示器自动黑屏，但此时系统中显示这个显示器在线。尝试在Windows下没有问题，百思不得其解。。。

**Comment by CLAY-BIOS** [comment]
> * 本子是T450s。
> * 最新的版本EFI。
> * 扩展坞为40A2，固件最新。
> * 外接显示器为DELL P2418D，2K 60HZ。
> * 连接线尝试过HDMI和DP。
>   故障现象为识别显示器亮屏5秒左右，显示器自动黑屏，但此时系统中显示这个显示器在线。尝试在Windows下没有问题，百思不得其解。。。

抱歉！我没有遇到过此问题。
你可以尝试以下操作。
1.接入电源适配器，然后将笔记本盖子关闭，看看外接显示器能否正常使用。
2.接入电源适配器，按下Fn + 4将内置显示器关闭，看看外接显示器能否正常使用。
3.尝试降低分辨率。
