### ISSUE TITLE
VGA support

### ISSUE THREAD

**Issue by juanpy0223** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#83]
hello, checking the config.plist file, I saw that it has a patch for VGA, but when I plug VGA cable, no signal on MONITOR... any suggestion... thanks for sharing your effort!!

**Comment by juanpy0223** [comment]
im using your OpenCore-0.6.6-v2.2, on Catalina

**Comment by CLAY-BIOS** [comment]
> hello, checking the config.plist file, I saw that it has a patch for VGA, but when I plug VGA cable, no signal on MONITOR... any suggestion... thanks for sharing your effort!!

I'm sorry! I can't add VGA support.

**Comment by juanpy0223** [comment]
Ok thank you
