### ISSUE TITLE
老大麻烦看看我的ts450s进不了OC是什么问题

### ISSUE THREAD

**Issue by recmess** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#85]
T450s的机器，装了以两个固态，一个装win11，一个装Catalina，网卡是BCM94360CS2+A/E转接卡。以前用的是[i3p9](https://github.com/i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi) 的EFI，能正常启动两个系统 ，因为老没更新，直接用了现在这个efi后，连oc菜单都没有了，直接进win11了，想请问要改哪些东西，谢谢

**Comment by CLAY-BIOS** [comment]
> T450s的机器，装了以两个固态，一个装win11，一个装Catalina，网卡是BCM94360CS2+A/E转接卡。以前用的是[i3p9](https://github.com/i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi) 的EFI，能正常启动两个系统 ，因为老没更新，直接用了现在这个efi后，连oc菜单都没有了，直接进win11了，想请问要改哪些东西，谢谢

直接替换掉原来的EFI就行了。

**Comment by recmess** [comment]
我用的是DW1820a的efi，能看到win11的盘符，并能进入，但看不见mac的盘符，我看ScanPolicy也是设为0，请问还有哪需要设置，谢谢

**Comment by CLAY-BIOS** [comment]
> 我用的是DW1820a的efi，能看到win11的盘符，并能进入，但看不见mac的盘符，我看ScanPolicy也是设为0，请问还有哪需要设置，谢谢

尝试在启动屏幕上选择Reset nvram来清除nvram。

**Comment by recmess** [comment]
选择Reset nvram来清除nvram后还是发现不了mac分区，但奇怪的是我用了0.6.2版本是可以发现mac分区的。进入后一切正常。系统是Catalina。

**Comment by recmess** [comment]
找到了方法：
UEFI→APFS→MinDate→-1
UEFI→APFS→MinVersion→-1
就可以发现APFS分区了，查了一下文档，意思是“允许使用任何版本的 APFS“，看了一下0.6.2版本都设为0，也可以发现apfs分区，暂时不清楚什么原因
