### ISSUE TITLE
MacOS Big Sur freezing issue

### ISSUE THREAD

**Issue by itzmanish** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#86]
Hey @CLAY-BIOS , let me start with showing my gratitude for the wonderful work that you have done here. So Thank you.

After installing MacOS Big Sur and using your EFIs, I find the system crash and freezing. Sometime it just go to login screen. Sometimes mouse pointer goes missing and screen freezes nothing works ( I have to restart with long press power button). Sometimes in idle situation it freezes (like I am browsing and all of sudden everything stops working).

I have verified that Memory/CPU usages is very low/idle at the time of issue. Please guide me if I am doing anything wrong which causes these issues. 

Thanks.

**Comment by PeaShooterR** [comment]
Have you tried disabling 'FeatureUnlock.kext'?
#57

**Comment by itzmanish** [comment]
no. i applied your fix. do I need to reset my nvram?

**Comment by itzmanish** [comment]
Ok. So after disabling 'FeatureUnlock.kext' it's working fine. No freezing issue till now.

**Comment by itzmanish** [comment]
@PeaShooterR do you know why big sur is taking more than 40s to boot? And is there way to optimize it?

**Comment by itzmanish** [comment]
One more think my camera output video with dark filter applied with some grains. Do you know what is the issue here?

**Comment by PeaShooterR** [comment]
I'm glad it helped!

 It takes me the same time to boot, you mean too slow? 
This is my first time using hackintosh, I thought this was normal, idk.

Seems that my camera works fine.
<img width="631" alt="Screen Shot 2022-01-13 at 13 13 36" src="https://user-images.githubusercontent.com/68700748/149265378-c115ee17-9d99-421f-b6fc-92a0b08e0703.png">

**Comment by itzmanish** [comment]
😭 My camera output looks like black filter applied and grainny. 😞 .

> It takes me the same time to boot, you mean too slow?

I read somewhere in the issues or somewhere in this repo that one guy was able to boot up in 25sec with some tweak in his EFI and he also shared his EFI. Now I am not able to find his message/issue/thread.
