### ISSUE TITLE
Cannot see HDD in OpenCore / macOS Recovery on T450s

### ISSUE THREAD

**Issue by similicious** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#87]
Hey everyone and thank you for supporting this notebook!
I'm new to Hackintosh, so please bear with me.

So, I created the Montery install usb according to this [guide](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#setting-up-the-installer): USB with GPT, `createinstallmedia`, mounted the EFI partition using [mountEFI](https://github.com/corpnewt/MountEFI) and copied your latest EFI files.

When I boot from the USB, in OpenCore I cannot see my existing macOS installation. Booting into macOS Recovery, in Disk Utility I also cannot see the SSD. I tried troubleshooting referencing the [docs](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/opencore-issues.html#can-t-see-macos-partitions) with no success.

Weirdly enough, when I use the EFI provided by the archived [T450s-Hackintosh project by racka98 ](https://github.com/racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore) it works.

Any idea, what I'm doing wrong? I'd really like to use this EFI, as this project is still maintained and up to date.

Best regards
similicious

**Comment by CLAY-BIOS** [comment]
> Hey everyone and thank you for supporting this notebook! I'm new to Hackintosh, so please bear with me.
> 
> So, I created the Montery install usb according to this [guide](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#setting-up-the-installer): USB with GPT, `createinstallmedia`, mounted the EFI partition using [mountEFI](https://github.com/corpnewt/MountEFI) and copied your latest EFI files.
> 
> When I boot from the USB, in OpenCore I cannot see my existing macOS installation. Booting into macOS Recovery, in Disk Utility I also cannot see the SSD. I tried troubleshooting referencing the [docs](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/opencore-issues.html#can-t-see-macos-partitions) with no success.
> 
> Weirdly enough, when I use the EFI provided by the archived [T450s-Hackintosh project by racka98 ](https://github.com/racka98/Lenovo-Thinkpad-T450-T450s-Hackintosh-Guide-Opencore) it works.
> 
> Any idea, what I'm doing wrong? I'd really like to use this EFI, as this project is still maintained and up to date.
> 
> Best regards similicious

Try selecting Reset nvram on the boot screen to clear nvRAM and make sure your BIOS Settings are correct.

**Comment by Qi-2007** [comment]
az，我也遇到了这个问题，我已经重置了 nvram，我尝试去修改我t450s的bios，结果发现所有选项都是灰色的，不知道你解决了吗

**Comment by similicious** [comment]
I reset my BIOS settings and set all the settings according to the readme. This let me see my HDD in macOS recovery.

However I also had to disable bluetooth as mentioned in #66 . 

Thank you!
