### ISSUE TITLE
laptop sleeps when lid is closed with hdmi connected

### ISSUE THREAD

**Issue by itzmanish** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#88]
My Thinkpad T450s goes to sleep when hdmi is connected.

Desired behaviour should be " It should not sleep and show the output to external display and treat external display as primary".

How to get this working?

**Comment by CLAY-BIOS** [comment]
> My Thinkpad T450s goes to sleep when hdmi is connected.
> 
> Desired behaviour should be " It should not sleep and show the output to external display and treat external display as primary".
> 
> How to get this working?

You need to plug in the power adapter. 
If you do not plug in the power adapter, you will go to sleep after closing the cover. 
reference resources: #40

**Comment by itzmanish** [comment]
seems like for now there is no override option to stop go to sleep when lid is closed and monitor is connected?

**Comment by itzmanish** [comment]
Also I am using a dp to hdmi adapter and since my system shows the external display as 1080p but I can see pixel on external display. Is it the issue of dp adapter or my system?

**Comment by CLAY-BIOS** [comment]
> seems like for now there is no override option to stop go to sleep when lid is closed and monitor is connected?

You can turn off the internal monitor through FN + 4, but you can't close the cover.

**Comment by itzmanish** [comment]
Ok. Thanks.
