### ISSUE TITLE
Thinkpad X1C 2015 选择Install后黑屏

### ISSUE THREAD

**Issue by Tryndaa** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore#96]
2k屏+I7 5600U+Intel AX200网卡 安装Monterey
BIOS全部按照说明设定。
从U盘启动后选择安装后黑屏。U盘目录下生成256K的OC日志文件，实际内容是空白的。
各位大佬有解决方法吗？

**Comment by FamilyCloud365** [comment]
@Tryndaa
你最后怎么解决的？我现在碰到同样的问题，很头痛
